# Generated by Django 5.2.4 on 2025-07-30 06:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kWh', models.DecimalField(decimal_places=4, help_text='Price in ₹ per kWh', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('quantity_kWh', models.DecimalField(decimal_places=3, help_text='Energy quantity in kWh', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this listing is available for trading')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Energy Listing',
                'verbose_name_plural': 'Energy Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=4, help_text='Opening price in ₹ per kWh', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('high', models.DecimalField(decimal_places=4, help_text='Highest price in ₹ per kWh', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('low', models.DecimalField(decimal_places=4, help_text='Lowest price in ₹ per kWh', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('close', models.DecimalField(decimal_places=4, help_text='Closing price in ₹ per kWh', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('datetime', models.DateTimeField(db_index=True, help_text='Timestamp for this price data point')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Energy Price History',
                'verbose_name_plural': 'Energy Price History',
                'ordering': ['-datetime'],
                'unique_together': {('datetime',)},
            },
        ),
        migrations.CreateModel(
            name='EnergyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of energy traded in kWh', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total transaction amount in ₹', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.energylisting')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Energy Transaction',
                'verbose_name_plural': 'Energy Transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Balance',
                'verbose_name_plural': 'User Balances',
            },
        ),
    ]
