# Generated by Django 5.2.4 on 2025-07-30 06:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytransaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='energytransaction',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='Original listing (nullable for flexibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.energylisting'),
        ),
        migrations.AlterField(
            model_name='energytransaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text="User's current balance in ₹", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
